config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("drama_2020.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

drama_2020/users/urls.py
from django.urls import path

from drama_2020.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

drama_2020/sound/models.py
from django.db import models

# Create your models here.
class LineOfScript(models.Model):
    number = models.DecimalField(max_digits=10, decimal_places=0, blank=False)
    label = models.CharField(max_length=20, blank=True)
    spoken_line = models.TextField(blank=True)
    audio_name = models.CharField(max_length=50, blank=True)
    note_description = models.TextField(blank=True)
    new_scene = models.BooleanField(default=False)
    scene_number = models.PositiveIntegerField(default=0, blank=True)
    highlight = models.BooleanField(default=False)

    class Meta:
        ordering = ['number']

# Delete from here down

class Scene(models.Model):
    scene_no = models.PositiveIntegerField()
    line_number_start = models.DecimalField(max_digits=10, decimal_places=0,blank=True)


    line_number_end = models.DecimalField(max_digits=10, decimal_places=0,blank=True)

class AudioFile(models.Model):
    name = models.CharField(max_length=50, blank=True)
    file_name = models.FileField(blank=True)
    line_number = models.DecimalField(max_digits=10, decimal_places=0,blank=True)

class Note(models.Model):
    description = models.TextField(blank=True)
    line_number = models.DecimalField(max_digits=10, decimal_places=0,blank=True)

class Script(models.Model):
    script_line = models.TextField()
    line_number = models.DecimalField(max_digits=10, decimal_places=0, blank=True)
    name = models.CharField(max_length=36, blank=True)

class Page(models.Model):
    start_line_number = models.PositiveIntegerField()

drama_2020/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

drama_2020/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

drama_2020/sound/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView, UpdateView


# Create your views here.
from .models import LineOfScript


def sound_home_view(request, *args, **kwargs):
    content = {

        'line_actual': LineOfScript.objects.all()
    }

    return render(request, 'sound/sound.html', content)


def edit_note(request, *args, **kwargs):
    pk = request.GET("pk")

    content = {
        "form"
    }
    return render(request, 'sound/edit_note.html', content)

class ScriptList(ListView):
    model = LineOfScript
    context_object_name = "line_actual"
    queryset = LineOfScript.objects.all()
    template_name = "sound/sound.html"

class ScriptUpdate(UpdateView):
    model = LineOfScript
    fields = "__all__"
    template_name = "sound/edit_note.html"
    success_url =  '/'

#["note_description", "highlight"]

drama_2020/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

drama_2020/sound/templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=PT+Sans+Caption|Righteous&display=swap" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href=" {% static 'sound/styles/page_styles.css' %} ">

    <title>Drama2020</title>

</head>

<body>
    {% block content %} replace me please {% endblock %}
</body>

</html>

drama_2020/sound/templates/edit_note.html
{% extends 'base.html' %} {% block content %}
<div class="page-wrapper2"></div>
<div class="header title">
    Editing Note
</div>

<div id="form-content">
    <form method="post">{% csrf_token %}
        <div id="description-title">
            Notes
        </div>
        <div id="description-box">
            {{form.note_description}}
        </div>

        <div id="highligh-box">
            {{form.highlight}} Highlight
        </div>
        <div id="button-bar">
            <input type="submit" value="Update" class="button">
            <a class="button" onclick="goBack()">Go back</a>
        </div>
    </form>
</div>
</div>

<div>

</div>

<script>
    function goBack() {
        window.history.back();
    }
</script>

{% endblock %}

drama_2020/sound/templates/navbar.html
<div class="container">
    <div class="navbar">
        <div class="title">
            <h1>sound</h1>
        </div>
        Page Number: <input type="number"> <input type="submit">
    </div>
    <div class="header">
        <div> Script </div>
        <div> Audio </div>
        <div> <a href="#">add Note </a></div>
    </div>
</div>

drama_2020/sound/templates/sound.html
{% extends 'base.html' %}{% block content %}


<div class="page-wrapper">
    <div class="upper_header">
        <img src="static/sound/img/logo3.png" alt="logo" id="tk-logo">
        <h1 class="main-title">Not So Terrible Parable</h1>
        <p id="funny-saying">Break a leg</p>
    </div>

    <div class="header">
        <!-- <img src="static/sound/img/Dashboard.png" alt="sound dashboard" id="image"> -->
        <div class="title" id="box1"> Script </div>
        <div class="title" id="box2"> Sound </div>
        <div class="title" id="box3"> Notes </div>
    </div>

    <div class="content">
        <table>
            {% for line in line_actual %} {% if line.highlight == True %}
            <tr class="data-table highlight">
                {% else %}
                <tr class="data-table">
                    {% endif %}

                    <td id="data-script">
                        <div id="script-section-1"> {{ line.number }}</div>
                        <div id="{{ line.label }}"> {{ line.label }} </div>
                        <div id="script-section-3"> {{ line.spoken_line }} </div>
                    </td>
                    <td id="data-sound">
                        {% if line.audio_name != '' %}
                        <audio src="static/sound/audio/{{line.audio_name}}.mp3" id="player{{ line.number }}" controls preload="metadata"> </audio> {% endif %}
                    </td>
                    <td id="data-notes">

                        {{ line.note_description }}
                        <a href="{% url 'update_script' line.pk %}">
                            <img src="static/sound/img/edit2.png" alt="edit button" class="button" id="editbutton"></a>

                    </td>
                </tr>
                {% endfor %}
        </table>
    </div>
    <!-- content END -->

    <div class="navbar">
        <h3>Scenes</h3>
        <ul>
            {% for line in line_actual %} {% if line.new_scene == True %}
            <li><a href="#{{ line.label }}" class="button">Scene {{ line.scene_number }}</a></li>
            {% endif %} {% endfor %}


        </ul>
    </div>
    <div class="footer">
        <img src="static/sound/img/logo.png" alt="logo" id="tk-logo-footer">
        <div id="footer-text">
            T&K Original
        </div>
        <br>
        <p id="funny-saying">
            Is it broken?
        </p>

    </div>
</div>
<!-- Page-wrapper END-->

{% endblock %}

drama_2020/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Drama 2020{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    
    {% endblock %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">Drama 2020</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>
      

    {% endblock javascript %}
  </body>
</html>
 

drama_2020/templates/pages/about.html
{% extends "base.html" %}

drama_2020/templates/pages/home.html
{% extends "base.html" %}

drama_2020/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

drama_2020/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}